"""Generate crawler-facing files from ``seo_config.ROUTES``.

Run after changing a public route, title, description or update date. CI/release
checks should use ``--check`` so metadata cannot drift across Python, Nginx and
the sitemap.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import content as T  # noqa: E402  (repo root is added deliberately above)
import seo_config as S  # noqa: E402


MAP_PATH = ROOT / "deploy" / "nginx" / "http-metadata-map.conf"
LOCATION_PATH = ROOT / "deploy" / "nginx" / "streamlit-location-metadata.conf"
ROBOTS_PATH = ROOT / "static" / "robots.txt"
SITEMAP_PATH = ROOT / "static" / "sitemap.xml"


def _nginx_quote(value: str) -> str:
    """Quote a static Nginx directive value while preserving runtime variables."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _map(name: str, values: list[tuple[str, str]], default: str) -> str:
    width = max([len(key) for key, _ in values] + [7]) + 2
    lines = [f"map $uri ${name} {{", f"    {'default':<{width}}{default};"]
    lines.extend(f"    {key:<{width}}{value};" for key, value in values)
    lines.append("}")
    return "\n".join(lines)


def _fallback_html(route: dict) -> str:
    current = route["path"]
    nav_items = [
        ("PrettyModels AI", "/"),
        ("Risk Disclosures", "/research-disclosures"),
        ("Legal Notice / Imprint", "/legal-notice"),
        ("Privacy", "/privacy-policy"),
    ]
    nav_links = []
    for label, path in nav_items:
        current_attr = ' aria-current="page"' if path == current else ""
        nav_links.append(
            f'<a href="{html.escape(path, quote=True)}"{current_attr}>'
            f"{html.escape(label)}</a>"
        )
    nav = "".join(nav_links)
    paragraphs = "".join(
        f"<p>{html.escape(paragraph)}</p>"
        for paragraph in [route["summary"], *route["fallback_paragraphs"]]
    )
    return (
        '<main id="pm-prerender">'
        '<header><a class="pm-prerender-brand" href="/">PrettyModels AI</a>'
        '<span>AI Research Lab</span></header>'
        f'<article><h1>{html.escape(route["heading"])}</h1>{paragraphs}'
        f'<nav aria-label="Research pages">{nav}</nav></article></main>'
    )


def _http_maps() -> str:
    routes = S.ROUTES
    titles = [(r["path"], _nginx_quote(r["title"])) for r in routes]
    descriptions = [(r["path"], _nginx_quote(r["description"])) for r in routes]
    canonicals = [(r["path"], _nginx_quote(r["path"])) for r in routes]
    robots = [
        (r["path"], _nginx_quote("index, follow, max-image-preview:large, max-snippet:-1"))
        for r in routes
    ]
    modified = [(r["path"], _nginx_quote(r["lastmod"])) for r in routes]
    fallback = [(r["path"], _nginx_quote(_fallback_html(r))) for r in routes]
    known = [(r["path"], "1") for r in routes]
    known.extend([
        ("~^/_stcore/", "1"),
        ("~^/static/", "1"),
        ("~^/media/", "1"),
        ("~^/component/", "1"),
        ("~^/app/static/", "1"),
        ("/favicon.png", "1"),
    ])

    blocks = [
        "# GENERATED by scripts/generate_seo_assets.py; do not edit by hand.",
        "# Include once at Nginx `http` scope.",
        _map("pm_meta_title", titles, _nginx_quote(T.PAGE_TITLE)),
        _map(
            "pm_meta_description",
            descriptions,
            _nginx_quote(T.PAGE_DESCRIPTION),
        ),
        _map("pm_canonical_path", canonicals, "$uri"),
        _map("pm_robots", robots, _nginx_quote("noindex, nofollow")),
        _map("pm_lastmod", modified, _nginx_quote(S.SITE_UPDATED_ISO)),
        _map("pm_prerender_body", fallback, _nginx_quote("")),
        _map("pm_known_route", known, "0"),
    ]
    return "\n\n".join(blocks) + "\n"


def _prerender_style() -> str:
    return (
        "<style id=\"pm-prerender-style\">"
        "#pm-prerender{box-sizing:border-box;max-width:1080px;margin:0 auto;"
        "padding:16px 48px 64px;color:#1A1A1A;background:#FBFAF8;"
        "font-family:Inter,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}"
        "#pm-prerender header{display:flex;align-items:baseline;gap:12px;"
        "padding:12px 0 18px;border-bottom:1px solid #E4E1DA}"
        "#pm-prerender header span{"
        "color:#6B6B6B;font-size:12px;letter-spacing:.08em;text-transform:uppercase}"
        ".pm-prerender-brand{font:600 18px Georgia,serif;color:#1A1A1A;text-decoration:none}"
        "#pm-prerender article{max-width:720px;padding-top:52px}"
        "#pm-prerender h1{font:500 48px/1.08 Georgia,serif;letter-spacing:-.02em;"
        "margin:10px 0 20px}#pm-prerender p{font-size:17px;line-height:1.65;margin:0 0 16px}"
        "#pm-prerender nav{display:flex;flex-wrap:wrap;gap:16px;margin-top:28px}"
        "#pm-prerender a{color:#3A34C0}"
        "#pm-prerender nav a{font-size:13px}"
        "@media(max-width:820px){#pm-prerender{padding:12px 20px 48px}"
        "#pm-prerender article{padding-top:34px}#pm-prerender h1{font-size:36px}}"
        "</style>"
    )


def _location_metadata() -> str:
    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Person",
                "@id": f"{S.AUTHOR_URL}#person",
                "name": S.AUTHOR_NAME,
                "url": S.AUTHOR_URL,
                "sameAs": ["https://quant-unit.com/"],
            },
            {
                "@type": "Organization",
                "@id": f"{S.SITE_URL}/#organization",
                "name": T.BRAND,
                "url": f"{S.SITE_URL}/",
                "logo": {
                    "@type": "ImageObject",
                    "url": f"{S.SITE_URL}/app/static/icon-512.png",
                    "width": 512,
                    "height": 512,
                },
                "founder": {"@id": f"{S.AUTHOR_URL}#person"},
                "sameAs": ["https://www.linkedin.com/company/prettymodels-ai"],
                "description": T.PAGE_DESCRIPTION,
            },
            {
                "@type": "WebSite",
                "@id": f"{S.SITE_URL}/#website",
                "name": T.BRAND,
                "url": f"{S.SITE_URL}/",
                "inLanguage": "en",
                "publisher": {"@id": f"{S.SITE_URL}/#organization"},
            },
            {
                "@type": "WebPage",
                "@id": f"{S.SITE_URL}$pm_canonical_path#webpage",
                "url": f"{S.SITE_URL}$pm_canonical_path",
                "name": "$pm_meta_title",
                "description": "$pm_meta_description",
                "dateModified": "$pm_lastmod",
                "inLanguage": "en",
                "isPartOf": {"@id": f"{S.SITE_URL}/#website"},
                "author": {"@id": f"{S.AUTHOR_URL}#person"},
                "publisher": {"@id": f"{S.SITE_URL}/#organization"},
            },
        ],
    }
    schema_json = json.dumps(schema, ensure_ascii=False, separators=(",", ":"))
    social_image = f"{S.SITE_URL}/app/static/social-preview-v2.png"
    image_alt = T.BRAND
    head = "".join([
        "<title>$pm_meta_title</title>",
        '<meta name="description" content="$pm_meta_description">',
        '<meta name="author" content="Christian Tausch">',
        '<meta name="robots" content="$pm_robots">',
        f'<link rel="canonical" href="{S.SITE_URL}$pm_canonical_path">',
        '<link rel="author" href="/legal-notice">',
        '<meta name="theme-color" content="#3A34C0">',
        '<meta name="color-scheme" content="light">',
        '<meta property="og:type" content="website">',
        '<meta property="og:locale" content="en_US">',
        f'<meta property="og:site_name" content="{T.BRAND}">',
        '<meta property="og:title" content="$pm_meta_title">',
        '<meta property="og:description" content="$pm_meta_description">',
        f'<meta property="og:url" content="{S.SITE_URL}$pm_canonical_path">',
        f'<meta property="og:image" content="{social_image}">',
        f'<meta property="og:image:secure_url" content="{social_image}">',
        '<meta property="og:image:type" content="image/png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{image_alt}">',
        '<meta name="twitter:card" content="summary_large_image">',
        '<meta name="twitter:title" content="$pm_meta_title">',
        '<meta name="twitter:description" content="$pm_meta_description">',
        f'<meta name="twitter:image" content="{social_image}">',
        f'<meta name="twitter:image:alt" content="{image_alt}">',
        '<link rel="manifest" href="/site.webmanifest">',
        f'<script type="application/ld+json">{schema_json}</script>',
        _prerender_style(),
    ])
    favicons = "".join([
        '<link rel="icon" href="/favicon.ico" sizes="any">',
        '<link rel="icon" type="image/png" sizes="32x32" '
        'href="/app/static/favicon-32x32.png">',
        '<link rel="icon" type="image/png" sizes="16x16" '
        'href="/app/static/favicon-16x16.png">',
        '<link rel="apple-touch-icon" sizes="180x180" '
        'href="/app/static/apple-touch-icon.png">',
    ])

    return "\n".join([
        "# GENERATED by scripts/generate_seo_assets.py; do not edit by hand.",
        "# Include inside the existing `location /` block, before proxy_pass.",
        "# A return-only Nginx `if` is safe here and prevents Streamlit soft 404s.",
        "if ($pm_known_route = 0) { return 404; }",
        'proxy_set_header Accept-Encoding "";',
        "sub_filter_once on;",
        "",
        "# Remove the retired production description during the deployment transition.",
        "sub_filter '<meta name=\"description\" content=\"Beat the market with an AI "
        "investment manager that compounds your wealth faster than ETFs.\">' '';",
        f"sub_filter '<title>Streamlit</title>' {_nginx_quote(head)};",
        f"sub_filter '<link rel=\"shortcut icon\" href=\"./favicon.png\" />' "
        f"{_nginx_quote(favicons)};",
        "",
        "# Useful content is present in the HTTP response before the websocket starts.",
        "# Streamlit's React root replaces this same-content fallback when the app renders.",
        "sub_filter '<div id=\"root\"></div>' "
        "'<div id=\"root\">$pm_prerender_body</div>';",
        "",
    ])


def _robots() -> str:
    return (
        "User-agent: *\n"
        "Allow: /\n\n"
        f"Sitemap: {S.SITE_URL}/sitemap.xml\n"
    )


def _sitemap() -> str:
    entries = "\n".join(
        f"  <url><loc>{html.escape(S.SITE_URL + route['path'])}</loc>"
        f"<lastmod>{route['lastmod']}</lastmod></url>"
        for route in S.ROUTES
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{entries}\n"
        "</urlset>\n"
    )


def generated_files() -> dict[Path, str]:
    return {
        MAP_PATH: _http_maps(),
        LOCATION_PATH: _location_metadata(),
        ROBOTS_PATH: _robots(),
        SITEMAP_PATH: _sitemap(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = parser.parse_args()
    stale: list[Path] = []

    for path, expected in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        print("Generated SEO files are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
        print("Run: python3 scripts/generate_seo_assets.py", file=sys.stderr)
        return 1
    if args.check:
        print("Generated SEO files are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
